// Keep user-facing copy separate from component logic for future localization.
export const strings = {
  product: 'MCWiiU Launcher',
  edition: 'Minecraft: Wii U Edition',
  architecture: 'Architecture v1',
  navigation: ['Home', 'Play', 'Mods', 'Textures', 'Accounts', 'Settings'],
  upcoming: 'Available in a future phase',
  welcome: 'A new home for Wii U Minecraft.',
  introduction: 'The launcher foundation is ready. Game import and runtime integration are the next step.',
  foundation: 'Launcher foundation',
  runtime: 'Runtime state',
  connecting: 'Connecting…',
  connected: 'Native bridge connected',
  bridgeUnavailable: 'Unable to connect to the native launcher. Try refreshing the status.',
  bridgeIncompatible: 'The launcher interface and native bridge are incompatible. Restart with a matching launcher build.',
  statusUnavailable: 'Unavailable',
  refresh: 'Refresh status',
  refreshing: 'Refreshing…',
  pending: 'Game runtime integration is pending.',
  supported: 'Patch 35 / v560',
  regions: 'USA · EUR · JPN',
  platform: 'Windows x64',
  development: 'Development',
  developerTools: 'Open developer tools',
  toolsUnavailable: 'Unable to open developer tools.',
  futureTitle: 'Built for the next step',
  futureDescription: 'Your game, mods, textures and accounts will have one place. Game files are supplied by you.',
};
