# Resolve junctions/symlinks as well as relative paths before checking ownership.
function(mcwiiu_require_external_path output_path)
    if (POLICY CMP0152)
        cmake_policy(SET CMP0152 NEW)
    endif()
    file(REAL_PATH "${CMAKE_SOURCE_DIR}" source_root)
    set(existing_parent "${output_path}")
    set(missing_suffix "")
    while (NOT EXISTS "${existing_parent}")
        cmake_path(GET existing_parent FILENAME component)
        cmake_path(GET existing_parent PARENT_PATH parent)
        if (parent STREQUAL existing_parent OR parent STREQUAL "")
            message(FATAL_ERROR "Cannot resolve output path: ${output_path}")
        endif()
        set(missing_suffix "${component}/${missing_suffix}")
        set(existing_parent "${parent}")
    endwhile()
    file(REAL_PATH "${existing_parent}" output_root)
    cmake_path(APPEND output_root "${missing_suffix}")
    cmake_path(NORMAL_PATH output_root)
    if (WIN32)
        string(TOLOWER "${source_root}" source_root)
        string(TOLOWER "${output_root}" output_root)
    endif()
    cmake_path(IS_PREFIX source_root "${output_root}" NORMALIZE inside_source)
    if (inside_source)
        message(FATAL_ERROR "Generated output must be outside the repository: ${output_path}")
    endif()
endfunction()
