# PackageProject 1.13 recreates aliases registered by Saucer's dependencies.
# vcpkg's add_library wrapper captures CMP0107 NEW, which rejects that operation.
# Keep the pinned source and patch only its external FetchContent checkout.
set(CMAKE_SOURCE_DIR "${PROJECT_ROOT}")
include("${PROJECT_ROOT}/cmake/ExternalOutput.cmake")
mcwiiu_require_external_path("${SOURCE_DIR}")
set(package_file "${SOURCE_DIR}/CMakeLists.txt")
file(READ "${package_file}" content)
set(marker "# Preserve an existing alias to the same target.")
string(FIND "${content}" "${marker}" patched)
if(NOT patched EQUAL -1)
    return()
endif()
set(original [=[    add_library(${PROJECT_NAMESPACE}${PROJECT_NAME} ALIAS ${PROJECT_NAME})]=])
set(replacement [=[    # Preserve an existing alias to the same target.
    if(TARGET ${PROJECT_NAMESPACE}${PROJECT_NAME})
      get_target_property(existing_alias ${PROJECT_NAMESPACE}${PROJECT_NAME} ALIASED_TARGET)
      if(NOT "${existing_alias}" STREQUAL "${PROJECT_NAME}")
        message(FATAL_ERROR "PackageProject alias points to a different target")
      endif()
    else()
      add_library(${PROJECT_NAMESPACE}${PROJECT_NAME} ALIAS ${PROJECT_NAME})
    endif()]=])
string(FIND "${content}" "${original}" position)
if(position EQUAL -1)
    message(FATAL_ERROR "Pinned PackageProject source no longer matches the compatibility patch")
endif()
string(REPLACE "${original}" "${replacement}" content "${content}")
file(WRITE "${package_file}" "${content}")
