name: Build Cemu

on:
  workflow_call:
    inputs:
      next_version_major:
        required: false
        type: string
      next_version_minor:
        required: false
        type: string

env:
  VCPKG_ROOT: "${{github.workspace}}/../_work/build/runtime/vcpkg-source"
  VCPKG_BINARY_SOURCES: 'clear;nuget,GitHub,readwrite'
  VCPKG_FORCE_DOWNLOADED_BINARIES: true
  
jobs:
  build-ubuntu:
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-22.04
            arch: x64
          - os: ubuntu-22.04-arm
            arch: arm
            
    name: build-ubuntu-${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    steps:
    - name: "Checkout repo"
      uses: actions/checkout@v6
      with:
        submodules: "recursive"
        fetch-depth: 0

    - name: Setup release mode parameters
      run: |
        echo "BUILD_MODE=release" >> $GITHUB_ENV
        echo "BUILD_FLAGS=" >> $GITHUB_ENV
        echo "Build mode is release"

    - name: Setup build flags for version
      if: ${{ inputs.next_version_major != '' }}
      run: |
        echo "[INFO] Version ${{ inputs.next_version_major }}.${{ inputs.next_version_minor }}"
        echo "BUILD_FLAGS=${{ env.BUILD_FLAGS }} -DEMULATOR_VERSION_MAJOR=${{ inputs.next_version_major }} -DEMULATOR_VERSION_MINOR=${{ inputs.next_version_minor }}" >> $GITHUB_ENV

    - name: "Install system dependencies"
      run: |
        sudo apt update -qq
        sudo apt install -y clang-15 cmake freeglut3-dev libgcrypt20-dev libglm-dev libgtk-3-dev libpulse-dev libsecret-1-dev libsystemd-dev libudev-dev nasm ninja-build libbluetooth-dev

    - name: "Bootstrap vcpkg"
      run: |
        mkdir -p ../_work/build/runtime
        git clone --local dependencies/vcpkg "$VCPKG_ROOT"
        bash "$VCPKG_ROOT/bootstrap-vcpkg.sh"

    - name: 'Setup NuGet Credentials for vcpkg'
      shell: 'bash'
      run: |
        mono `"$VCPKG_ROOT/vcpkg" fetch nuget | tail -n 1` \
        sources add \
        -source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" \
        -storepasswordincleartext \
        -name "GitHub" \
        -username "${{ github.repository_owner }}" \
        -password "${{ secrets.GITHUB_TOKEN }}"
        mono `"$VCPKG_ROOT/vcpkg" fetch nuget | tail -n 1` \
        setapikey "${{ secrets.GITHUB_TOKEN }}" \
        -source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"
        
    - name: "cmake"
      run: |
        cmake -S . -B ../_work/build/runtime ${{ env.BUILD_FLAGS }} -DCMAKE_BUILD_TYPE=${{ env.BUILD_MODE }} -DCMAKE_C_COMPILER=/usr/bin/clang-15 -DCMAKE_CXX_COMPILER=/usr/bin/clang++-15 -G Ninja -DCMAKE_MAKE_PROGRAM=/usr/bin/ninja

    - name: "Build Cemu"
      run: |
        cmake --build ../_work/build/runtime

    - name: Prepare artifact
      id: artifact
      run: |
        mkdir -p ../_artifacts/portable
        cp ../_work/build/runtime/bin/release/Cemu_release ../_artifacts/portable/Cemu
        cd ../_artifacts/portable
        echo "path=$PWD/Cemu" >> "$GITHUB_OUTPUT"

    - name: Upload artifact
      uses: actions/upload-artifact@v6
      with:
        name: cemu-bin-linux-${{ matrix.arch }}
        path: ${{ steps.artifact.outputs.path }}

  build-appimage:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-22.04
            arch: x64
          - os: ubuntu-22.04-arm
            arch: arm
            
    name: build-appimage-${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    needs: build-ubuntu
    steps:
    - name: Checkout Upstream Repo
      uses: actions/checkout@v6

    - uses: actions/download-artifact@v8
      with:
        name: cemu-bin-linux-${{ matrix.arch }}
        path: ../_work/staging/appimage/bin

    - name: "Install system dependencies"
      run: |
        sudo apt update -qq
        sudo apt install -y clang-15 cmake freeglut3-dev libgcrypt20-dev libglm-dev libgtk-3-dev libpulse-dev libsecret-1-dev libsystemd-dev nasm ninja-build appstream libbluetooth-dev

    - name: "Build AppImage"
      id: artifact
      working-directory: ../_work/staging/appimage
      env:
        CEMU_PACKAGING_ROOT: ${{ github.workspace }}/../_work/staging/appimage
        CEMU_SOURCE_ROOT: ${{ github.workspace }}
      run: |
        mkdir -p dist
        cp -r "$CEMU_SOURCE_ROOT/dist/linux" dist/
        cp -r "$CEMU_SOURCE_ROOT/bin/." bin/
        export LD_LIBRARY_PATH="/usr/local/lib:$LD_LIBRARY_PATH"
        export DEPLOY_GTK_VERSION=3
        dist/linux/appimage.sh ${{ runner.arch }}
        mkdir -p "$CEMU_SOURCE_ROOT/../_artifacts/portable"
        cp artifacts/*.AppImage "$CEMU_SOURCE_ROOT/../_artifacts/portable/"
        cd "$CEMU_SOURCE_ROOT/../_artifacts/portable"
        echo "path=$PWD/*.AppImage" >> "$GITHUB_OUTPUT"

    - name: Upload artifact
      uses: actions/upload-artifact@v6
      with:
        name: cemu-appimage-${{ matrix.arch }}
        path: ${{ steps.artifact.outputs.path }}

  build-windows:
    runs-on: windows-2022
    steps:
    - name: "Checkout repo"
      uses: actions/checkout@v6
      with:
        submodules: "recursive"

    - name: Setup release mode parameters
      run: |
        echo "BUILD_MODE=release" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
        echo "BUILD_FLAGS=" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
        echo "Build mode is release"

    - name: Setup build flags for version
      if: ${{ inputs.next_version_major != '' }}
      run: |
        echo "[INFO] Version ${{ inputs.next_version_major }}.${{ inputs.next_version_minor }}"
        echo "BUILD_FLAGS=${{ env.BUILD_FLAGS }} -DEMULATOR_VERSION_MAJOR=${{ inputs.next_version_major }} -DEMULATOR_VERSION_MINOR=${{ inputs.next_version_minor }}" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append

    - name: "Setup cmake"
      uses: jwlawson/actions-setup-cmake@v2
      with:
        cmake-version: '3.29.0'

    - name: "Bootstrap vcpkg"
      run: |
        New-Item -ItemType Directory -Force ../_work/build/runtime | Out-Null
        git clone --local dependencies/vcpkg "$Env:VCPKG_ROOT"
        & "$Env:VCPKG_ROOT/bootstrap-vcpkg.bat"

    - name: 'Setup NuGet Credentials for vcpkg'
      shell: 'bash'
      run: |
        `"$VCPKG_ROOT/vcpkg.exe" fetch nuget | tail -n 1` \
        sources add \
        -source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" \
        -storepasswordincleartext \
        -name "GitHub" \
        -username "${{ github.repository_owner }}" \
        -password "${{ secrets.GITHUB_TOKEN }}"
        `"$VCPKG_ROOT/vcpkg.exe" fetch nuget | tail -n 1` \
        setapikey "${{ secrets.GITHUB_TOKEN }}" \
        -source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"

    - name: "cmake"
      run: |
        echo "[INFO] BUILD_FLAGS: ${{ env.BUILD_FLAGS }}"
        echo "[INFO] BUILD_MODE: ${{ env.BUILD_MODE }}"
        cmake -S . -B ../_work/build/runtime ${{ env.BUILD_FLAGS }} -DCMAKE_BUILD_TYPE=${{ env.BUILD_MODE }} -DVCPKG_INSTALL_OPTIONS="--clean-after-build"

    - name: "Build Cemu"
      run: |
        cmake --build ../_work/build/runtime --config ${{ env.BUILD_MODE }}

    - name: Prepare artifact
      id: artifact
      run: |
        New-Item -ItemType Directory -Force ../_work/staging/windows/src/resource, ../_artifacts/portable | Out-Null
        Copy-Item bin ../_work/staging/windows/bin -Recurse
        Copy-Item src/resource/installer.nsi, src/resource/logo_icon.ico ../_work/staging/windows/src/resource/
        Copy-Item LICENSE.txt ../_work/staging/windows/
        Copy-Item ../_work/build/runtime/bin/Release/Cemu_release.exe ../_artifacts/portable/Cemu.exe
        Copy-Item ../_artifacts/portable/Cemu.exe ../_work/staging/windows/bin/Cemu.exe
        $executable = Get-Item -LiteralPath '../_artifacts/portable/Cemu.exe'
        "path=$($executable.FullName)" >> $env:GITHUB_OUTPUT

    - name: Build NSIS Installer
      shell: cmd
      working-directory: ../_work/staging/windows/src/resource
      run: |
        makensis /DPRODUCT_VERSION=${{ inputs.next_version_major }}.${{ inputs.next_version_minor }} installer.nsi

    - name: Prepare installer artifact
      id: installer
      run: |
        New-Item -ItemType Directory -Force ../_artifacts/installer | Out-Null
        Copy-Item ../_work/staging/windows/src/resource/cemu-*-windows-x64-installer.exe ../_artifacts/installer/
        $installerDirectory = Get-Item -LiteralPath '../_artifacts/installer'
        "path=$($installerDirectory.FullName)/cemu-${{ inputs.next_version_major }}.${{ inputs.next_version_minor }}-windows-x64-installer.exe" >> $env:GITHUB_OUTPUT

    - name: Upload artifact
      uses: actions/upload-artifact@v6
      with:
        name: cemu-bin-windows-x64
        path: ${{ steps.artifact.outputs.path }}

    - name: Upload NSIS Installer
      uses: actions/upload-artifact@v6
      with:
        name: cemu-installer-windows-x64
        path: ${{ steps.installer.outputs.path }}

  build-macos:
    runs-on: macos-15
    strategy:
      fail-fast: false
      matrix:
        arch: [x86_64, arm64]
    steps:
    - name: "Checkout repo"
      uses: actions/checkout@v6
      with:
        submodules: "recursive"

    - name: Setup release mode parameters
      run: |
        echo "BUILD_MODE=release" >> $GITHUB_ENV
        echo "BUILD_FLAGS=" >> $GITHUB_ENV
        echo "Build mode is release"

    - name: Setup build flags for version
      if: ${{ inputs.next_version_major != '' }}
      run: |
        echo "[INFO] Version ${{ inputs.next_version_major }}.${{ inputs.next_version_minor }}"
        echo "BUILD_FLAGS=${{ env.BUILD_FLAGS }} -DEMULATOR_VERSION_MAJOR=${{ inputs.next_version_major }} -DEMULATOR_VERSION_MINOR=${{ inputs.next_version_minor }}" >> $GITHUB_ENV

    - name: "Install system dependencies"
      run: |
        # Removing azure/bicep and aws to silence warnings in Github Actions
        brew uninstall bicep
        brew untap aws/tap azure/bicep
        brew update
        brew install nasm automake libtool mono

    - name: "Install molten-vk"
      run: |
        mkdir -p ../_work/cache/molten-vk
        cd ../_work/cache/molten-vk
        curl -L -O https://github.com/KhronosGroup/MoltenVK/releases/download/v1.4.1/MoltenVK-macos-privateapi.tar
        tar xf MoltenVK-macos-privateapi.tar
        sudo mkdir -p /usr/local/lib
        sudo cp MoltenVK/MoltenVK/dynamic/dylib/macOS/libMoltenVK.dylib /usr/local/lib

    - name: "Setup cmake"
      uses: jwlawson/actions-setup-cmake@v2
      with:
        cmake-version: '3.29.0'

    - name: "Bootstrap vcpkg"
      run: |
        mkdir -p ../_work/build/runtime
        git clone --local dependencies/vcpkg "$VCPKG_ROOT"
        bash "$VCPKG_ROOT/bootstrap-vcpkg.sh"

    - name: 'Setup NuGet Credentials for vcpkg'
      shell: 'bash'
      run: |
        mono `"$VCPKG_ROOT/vcpkg" fetch nuget | tail -n 1` \
        sources add \
        -source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" \
        -storepasswordincleartext \
        -name "GitHub" \
        -username "${{ github.repository_owner }}" \
        -password "${{ secrets.GITHUB_TOKEN }}"
        mono `"$VCPKG_ROOT/vcpkg" fetch nuget | tail -n 1` \
        setapikey "${{ secrets.GITHUB_TOKEN }}" \
        -source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"

    - name: "cmake"
      run: |
        cmake -S . -B ../_work/build/runtime ${{ env.BUILD_FLAGS }} \
        -DCMAKE_BUILD_TYPE=${{ env.BUILD_MODE }} \
        -DCMAKE_OSX_ARCHITECTURES=${{ matrix.arch }} \
        -DMACOS_BUNDLE=ON \
        -G Ninja

    - name: "Build Cemu"
      run: |
        cmake --build ../_work/build/runtime

    - name: Prepare artifact
      id: artifact
      run: |
        mkdir -p ../_work/staging/macos/Cemu_app ../_artifacts/portable
        mv ../_work/build/runtime/bin/release/Cemu_release.app ../_work/staging/macos/Cemu_app/Cemu.app
        mv ../_work/staging/macos/Cemu_app/Cemu.app/Contents/MacOS/Cemu_release ../_work/staging/macos/Cemu_app/Cemu.app/Contents/MacOS/Cemu
        sed -i '' 's/Cemu_release/Cemu/g' ../_work/staging/macos/Cemu_app/Cemu.app/Contents/Info.plist
        codesign --entitlements ${{github.workspace}}/src/resource/cemu.macos.entitlements --force --deep --preserve-metadata=entitlements,requirements,flags,runtime --sign - --timestamp --options runtime ../_work/staging/macos/Cemu_app/Cemu.app/Contents/MacOS/Cemu
        ln -s /Applications ../_work/staging/macos/Cemu_app/Applications
        hdiutil create ../_work/staging/macos/tmp.dmg -ov -volname "Cemu" -fs HFS+ -srcfolder "../_work/staging/macos/Cemu_app"
        hdiutil convert ../_work/staging/macos/tmp.dmg -format UDZO -o ../_artifacts/portable/Cemu.dmg
        rm ../_work/staging/macos/tmp.dmg
        cd ../_artifacts/portable
        echo "path=$PWD/Cemu.dmg" >> "$GITHUB_OUTPUT"

    - name: Upload artifact
      uses: actions/upload-artifact@v6
      with:
        name: cemu-bin-macos-${{ matrix.arch }}
        path: ${{ steps.artifact.outputs.path }}
